//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC5App.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_BOOK()
        {
            this.APP_PURCHASE = new HashSet<APP_PURCHASE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string GANRE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE_REG { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_PURCHASE> APP_PURCHASE { get; set; }
    }
}
