//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC5App.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_HISTORY
    {
        public decimal ID { get; set; }
        public string OPERATION { get; set; }
        public decimal ID_BOOK { get; set; }
    }
}
