//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC5App.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_IMG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_IMG()
        {
            this.APP_BOOK = new HashSet<APP_BOOK>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public byte[] IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_BOOK> APP_BOOK { get; set; }
    }
}
