//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC5App.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PURCHASE
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> DATE_PURCHASE { get; set; }
        public Nullable<decimal> ID_USER { get; set; }
        public decimal ID_BOOK { get; set; }
    
        public virtual APP_BOOK APP_BOOK { get; set; }
        public virtual APP_USER APP_USER { get; set; }
    }
}
