//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC5App.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_BOOK> APP_BOOK { get; set; }
        public virtual DbSet<APP_HISTORY> APP_HISTORY { get; set; }
        public virtual DbSet<APP_IMG> APP_IMG { get; set; }
        public virtual DbSet<APP_PURCHASE> APP_PURCHASE { get; set; }
        public virtual DbSet<APP_USER> APP_USER { get; set; }
    }
}
